// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI-Pf-g6TZ4MEs-M-9IXs5mZSXeoOq5xw',
    appId: '1:102376726584:web:4a9ce6d00edc7ab97f86cd',
    messagingSenderId: '102376726584',
    projectId: 'flutter-618c8',
    authDomain: 'flutter-618c8.firebaseapp.com',
    databaseURL: 'https://flutter-618c8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-618c8.appspot.com',
    measurementId: 'G-1LZ1JPM5LT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEW1VbQneRoXZK7sDIZw0y2H0GqvcbZ9k',
    appId: '1:102376726584:android:fe57e0a86ed6c8047f86cd',
    messagingSenderId: '102376726584',
    projectId: 'flutter-618c8',
    databaseURL: 'https://flutter-618c8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-618c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPYz4xJExfWeI840sWKltW-F1BsAknkaU',
    appId: '1:102376726584:ios:9da67dfbb05f73e37f86cd',
    messagingSenderId: '102376726584',
    projectId: 'flutter-618c8',
    databaseURL: 'https://flutter-618c8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-618c8.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPYz4xJExfWeI840sWKltW-F1BsAknkaU',
    appId: '1:102376726584:ios:d988df99c8de23ec7f86cd',
    messagingSenderId: '102376726584',
    projectId: 'flutter-618c8',
    databaseURL: 'https://flutter-618c8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-618c8.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
